=== claudiorasf/airport-project-xml/airport.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <!-- Global Types -->
    <xs:simpleType name="AirportName">
        <xs:restriction base="xs:string">
            <xs:enumeration value="London International Airport (XYU)"/>      
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="TimeType">
        <xs:restriction base="xs:string">
            <xs:pattern value="\d{2}:\d{2}"/>
        </xs:restriction>
    </xs:simpleType>    

    <xs:simpleType name="Airline">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Air Canada"/>
            <xs:enumeration value="Air Transat"/>
            <xs:enumeration value="Sunwing"/>
            <xs:enumeration value="Swoop"/>
            <xs:enumeration value="WestJet"/>
            <xs:enumeration value="WestJet Encore"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="Flight">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="1" />
            <xs:maxInclusive value="9999" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="Arriving_Departing">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Abbotsford"/>
            <xs:enumeration value="Calgary"/>
            <xs:enumeration value="Cancun"/>
            <xs:enumeration value="Cayo Santa Maria"/>
            <xs:enumeration value="Edmonton"/>
            <xs:enumeration value="Hamilton"/>
            <xs:enumeration value="Las Vegas"/>
            <xs:enumeration value="Montego Bay"/>
            <xs:enumeration value="Montreal"/>
            <xs:enumeration value="Orlando"/>
            <xs:enumeration value="Ottawa"/>
            <xs:enumeration value="Puerto Plata"/>
            <xs:enumeration value="Punta Cana"/>
            <xs:enumeration value="Sault Ste Marie"/>
            <xs:enumeration value="Toronto"/>
            <xs:enumeration value="Varadero"/>
            <xs:enumeration value="Winnipeg"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="ArrivalStatus">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Arrived"/>
            <xs:enumeration value="Cancelled"/>
            <xs:enumeration value="Diverted"/>
            <xs:enumeration value="Early"/>
            <xs:enumeration value="Late"/>
            <xs:enumeration value="On Time"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="DepartureStatus">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Cancelled"/>
            <xs:enumeration value="Departed"/>
            <xs:enumeration value="Delayed"/>
            <xs:enumeration value="On Time"/>
        </xs:restriction>
    </xs:simpleType>

    <!-- Instance document structure -->
    <xs:element name="airport">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="lastUpdated" minOccurs="0" maxOccurs="1">
                    <xs:complexType>
                    <xs:sequence>
                        <xs:element name="date" type="xs:date" />
                        <xs:element name="time" type="xs:time"/>
                    </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="arrivals" minOccurs="0" maxOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="arrival" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:all>
                                        <xs:element name="airline" type="Airline" minOccurs="1" maxOccurs="1" />
                                        <xs:element name="flight" type="Flight" minOccurs="1" maxOccurs="1" />
                                        <xs:element name="arrivingFrom" type="Arriving_Departing" minOccurs="1" maxOccurs="1" />
                                        <xs:element name="scheduledTime" type="TimeType" minOccurs="1" maxOccurs="1" />
                                        <xs:element name="actualTime" type="TimeType" minOccurs="1" maxOccurs="1" />
                                        <xs:element name="status" type="ArrivalStatus" minOccurs="1" maxOccurs="1" />
                                    </xs:all>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="departures" minOccurs="0" maxOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="departure" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:all>
                                        <xs:element name="airline" type="Airline" minOccurs="1" maxOccurs="1" />
                                        <xs:element name="flight" type="Flight" minOccurs="1" maxOccurs="1" />
                                        <xs:element name="departingTo" type="Arriving_Departing" minOccurs="1" maxOccurs="1" />
                                        <xs:element name="scheduledTime" type="TimeType" minOccurs="1" maxOccurs="1" />
                                        <xs:element name="actualTime" type="TimeType" minOccurs="1" maxOccurs="1" />
                                        <xs:element name="status" type="DepartureStatus" minOccurs="1" maxOccurs="1" />
                                    </xs:all>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>   
            </xs:sequence>
            <xs:attribute name="name" type="AirportName" />
        </xs:complexType>
    </xs:element>
</xs:schema>

=== claudiorasf/airport-project-xml/airport-two.xml
<?xml version="1.0" encoding="utf-8" ?>
<airport 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:noNamespaceSchemaLocation="airport.xsd"
    name="London International Airport (XYU)">
    <lastUpdated>
        <date>2020-02-06</date>
        <time>22:44:56</time>
    </lastUpdated>
    <arrivals>
        <arrival>
            <airline>Swoop</airline>
            <flight>833</flight>
            <arrivingFrom>Las Vegas</arrivingFrom>
            <scheduledTime>19:37</scheduledTime>
            <actualTime>20:16</actualTime>
            <status>Arrived</status>
        </arrival>
        <arrival>
            <airline>Air Canada</airline>
            <flight>8661</flight>
            <arrivingFrom>Ottawa</arrivingFrom>
            <scheduledTime>21:15</scheduledTime>
            <actualTime>23:16</actualTime>
            <status>Late</status>
        </arrival>
        <arrival>
            <airline>Swoop</airline>
            <flight>342</flight>
            <arrivingFrom>Abbotsford</arrivingFrom>
            <scheduledTime>21:52</scheduledTime>
            <actualTime>22:22</actualTime>
            <status>Arrived</status>
        </arrival>
        <arrival>
            <airline>Air Canada</airline>
            <flight>8655</flight>
            <arrivingFrom>Toronto</arrivingFrom>
            <scheduledTime>22:16</scheduledTime>
            <actualTime>22:43</actualTime>
            <status>Arrived</status>
        </arrival>
        <arrival>
            <airline>WestJet</airline>
            <flight>3507</flight>
            <arrivingFrom>Toronto</arrivingFrom>
            <scheduledTime>23:20</scheduledTime>
            <actualTime>00:13</actualTime>
            <status>Late</status>
        </arrival>
        <arrival>
            <airline>WestJet</airline>
            <flight>736</flight>
            <arrivingFrom>Calgary</arrivingFrom>
            <scheduledTime>00:16</scheduledTime>
            <actualTime>00:04</actualTime>
            <status>Early</status>
        </arrival>
        <arrival>
            <airline>Air Transat</airline>
            <flight>815</flight>
            <arrivingFrom>Puerto Plata</arrivingFrom>
            <scheduledTime>02:15</scheduledTime>
            <actualTime>02:15</actualTime>
            <status>On Time</status>
        </arrival>
        <arrival>
            <airline>Air Canada</airline>
            <flight>8643</flight>
            <arrivingFrom>Toronto</arrivingFrom>
            <scheduledTime>08:46</scheduledTime>
            <actualTime>08:46</actualTime>
            <status>On Time</status>
        </arrival>
        <arrival>
            <airline>WestJet</airline>
            <flight>3517</flight>
            <arrivingFrom>Toronto</arrivingFrom>
            <scheduledTime>10:03</scheduledTime>
            <actualTime>10:03</actualTime>
            <status>On Time</status>
        </arrival>
        <arrival>
            <airline>Swoop</airline>
            <flight>208</flight>
            <arrivingFrom>Edmonton</arrivingFrom>
            <scheduledTime>11:38</scheduledTime>
            <actualTime>11:38</actualTime>
            <status>On Time</status>
        </arrival>
    </arrivals>
    <departures>
        <departure>
            <airline>Swoop</airline>
            <flight>834</flight>
            <departingTo>Las Vegas</departingTo>
            <scheduledTime>20:30</scheduledTime>
            <actualTime>21:33</actualTime>
            <status>Departed</status>
        </departure>
        <departure>
            <airline>Swoop</airline>
            <flight>539</flight>
            <departingTo>Edmonton</departingTo>
            <scheduledTime>22:40</scheduledTime>
            <actualTime>23:15</actualTime>
            <status>Delayed</status>
        </departure>
        <departure>
            <airline>Air Canada</airline>
            <flight>8640</flight>
            <departingTo>Toronto</departingTo>
            <scheduledTime>05:55</scheduledTime>
            <actualTime>05:55</actualTime>
            <status>On Time</status>
        </departure>
        <departure>
            <airline>WestJet</airline>
            <flight>735</flight>
            <departingTo>Calgary</departingTo>
            <scheduledTime>06:00</scheduledTime>
            <actualTime>06:00</actualTime>
            <status>On Time</status>
        </departure>
        <departure>
            <airline>Air Canada</airline>
            <flight>8658</flight>
            <departingTo>Ottawa</departingTo>
            <scheduledTime>06:15</scheduledTime>
            <actualTime>06:15</actualTime>
            <status>On Time</status>
        </departure>
        <departure>
            <airline>WestJet</airline>
            <flight>3504</flight>
            <departingTo>Toronto</departingTo>
            <scheduledTime>06:55</scheduledTime>
            <actualTime>06:55</actualTime>
            <status>On Time</status>
        </departure>
        <departure>
            <airline>Air Canada</airline>
            <flight>8644</flight>
            <departingTo>Toronto</departingTo>
            <scheduledTime>09:10</scheduledTime>
            <actualTime>09:10</actualTime>
            <status>On Time</status>
        </departure>
        <departure>
            <airline>WestJet</airline>
            <flight>3516</flight>
            <departingTo>Toronto</departingTo>
            <scheduledTime>10:35</scheduledTime>
            <actualTime>10:35</actualTime>
            <status>On Time</status>
        </departure>
        <departure>
            <airline>Air Canada</airline>
            <flight>8646</flight>
            <departingTo>Toronto</departingTo>
            <scheduledTime>12:05</scheduledTime>
            <actualTime>12:05</actualTime>
            <status>On Time</status>
        </departure>
        <departure>
            <airline>Swoop</airline>
            <flight>221</flight>
            <departingTo>Abbotsford</departingTo>
            <scheduledTime>12:25</scheduledTime>
            <actualTime>12:25</actualTime>
            <status>On Time</status>
        </departure>
    </departures>
</airport>

=== claudiorasf/airport-project-xml/airport-one.xml
<?xml version="1.0" encoding="utf-8" ?>
<airport 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:noNamespaceSchemaLocation="airport.xsd"
    name="London International Airport (XYU)">
    <lastUpdated>
        <date>2020-01-23</date>
        <time>12:00:56</time>
    </lastUpdated>
    <arrivals>
        <arrival>
            <airline>Air Canada</airline>
            <flight>8643</flight>
            <arrivingFrom>Toronto</arrivingFrom>
            <scheduledTime>08:46</scheduledTime>
            <actualTime>08:47</actualTime>
            <status>Arrived</status>
        </arrival>
        <arrival>
            <airline>Sunwing</airline>
            <flight>374</flight>
            <arrivingFrom>Sault Ste Marie</arrivingFrom>
            <scheduledTime>09:25</scheduledTime>
            <actualTime>09:27</actualTime>
            <status>Arrived</status>
        </arrival>
        <arrival>
            <airline>WestJet</airline>
            <flight>3517</flight>
            <arrivingFrom>Toronto</arrivingFrom>
            <scheduledTime>10:03</scheduledTime>
            <actualTime>10:02</actualTime>
            <status>Arrived</status>
        </arrival>
        <arrival>
            <airline>Swoop</airline>
            <flight>208</flight>
            <arrivingFrom>Edmonton</arrivingFrom>
            <scheduledTime>11:38</scheduledTime>
            <actualTime>11:55</actualTime>
            <status>Late</status>
        </arrival>
        <arrival>
            <airline>Air Canada</airline>
            <flight>8645</flight>
            <arrivingFrom>Toronto</arrivingFrom>
            <scheduledTime>11:41</scheduledTime>
            <actualTime>11:31</actualTime>
            <status>Early</status>
        </arrival>
        <arrival>
            <airline>Air Canada</airline>
            <flight>8659</flight>
            <arrivingFrom>Ottawa</arrivingFrom>
            <scheduledTime>13:50</scheduledTime>
            <actualTime>13:47</actualTime>
            <status>Early</status>
        </arrival>
        <arrival>
            <airline>Swoop</airline>
            <flight>683</flight>
            <arrivingFrom>Cancun</arrivingFrom>
            <scheduledTime>14:23</scheduledTime>
            <actualTime>14:25</actualTime>
            <status>Late</status>
        </arrival>
        <arrival>
            <airline>Air Canada</airline>
            <flight>8649</flight>
            <arrivingFrom>Toronto</arrivingFrom>
            <scheduledTime>14:31</scheduledTime>
            <actualTime>14:31</actualTime>
            <status>On Time</status>
        </arrival>
        <arrival>
            <airline>Air Canada</airline>
            <flight>8665</flight>
            <arrivingFrom>Montreal</arrivingFrom>
            <scheduledTime>15:08</scheduledTime>
            <actualTime>15:08</actualTime>
            <status>On Time</status>
        </arrival>
        <arrival>
            <airline>Air Transat</airline>
            <flight>847</flight>
            <arrivingFrom>Cancun</arrivingFrom>
            <scheduledTime>15:10</scheduledTime>
            <actualTime>15:10</actualTime>
            <status>Arrived</status>
        </arrival>
    </arrivals>
    <departures>
        <departure>
            <airline>Air Canada</airline>
            <flight>8644</flight>
            <departingTo>Toronto</departingTo>
            <scheduledTime>09:10</scheduledTime>
            <actualTime>09:14</actualTime>
            <status>Departed</status>
        </departure>
        <departure>
            <airline>Sunwing</airline>
            <flight>374</flight>
            <departingTo>Varadero</departingTo>
            <scheduledTime>10:15</scheduledTime>
            <actualTime>10:17</actualTime>
            <status>Departed</status>
        </departure>
        <departure>
            <airline>WestJet</airline>
            <flight>539</flight>
            <departingTo>Edmonton</departingTo>
            <scheduledTime>09:10</scheduledTime>
            <actualTime>09:12</actualTime>
            <status>Departed</status>
        </departure>
        <departure>
            <airline>Air Canada</airline>
            <flight>462</flight>
            <departingTo>Punta Cana</departingTo>
            <scheduledTime>09:30</scheduledTime>
            <actualTime>10:00</actualTime>
            <status>Delayed</status>
        </departure>
        <departure>
            <airline>Swoop</airline>
            <flight>3516</flight>
            <departingTo>Toronto</departingTo>
            <scheduledTime>10:35</scheduledTime>
            <actualTime>10:34</actualTime>
            <status>Departed</status>
        </departure>
        <departure>
            <airline>Air Canada</airline>
            <flight>8646</flight>
            <departingTo>Toronto</departingTo>
            <scheduledTime>12:05</scheduledTime>
            <actualTime>12:05</actualTime>
            <status>On Time</status>
        </departure>
        <departure>
            <airline>Air Canada</airline>
            <flight>221</flight>
            <departingTo>Abbotsford</departingTo>
            <scheduledTime>12:25</scheduledTime>
            <actualTime>12:25</actualTime>
            <status>On Time</status>
        </departure>
        <departure>
            <airline>Swoop</airline>
            <flight>8648</flight>
            <departingTo>Toronto</departingTo>
            <scheduledTime>13:25</scheduledTime>
            <actualTime>13:25</actualTime>
            <status>On Time</status>
        </departure>
        <departure>
            <airline>Air Transat</airline>
            <flight>8660</flight>
            <departingTo>Ottawa</departingTo>
            <scheduledTime>14:15</scheduledTime>
            <actualTime>14:15</actualTime>
            <status>On Time</status>
        </departure>
        <departure>
            <airline>Swoop</airline>
            <flight>8652</flight>
            <departingTo>Montreal</departingTo>
            <scheduledTime>14:55</scheduledTime>
            <actualTime>14:55</actualTime>
            <status>On Time</status>
        </departure>
    </departures>
</airport>
